# Generated by Django 5.0.6 on 2024-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_ssn',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
